version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  gem_cache:
  postgres: