version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web
    tty: true
    stdin_open: true

  database:
    image: postgres
    env_file:
      - .env/development/database
    ports:
    - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  db-migrator:
    image: caueguedes/auto-force:prod
    command: [ "./wait-for", "--timeout=3000", "database:5432", "--",
               "bin/rails", "db:migrate" ]
    env_file:
      - .env/development/database
      - .env/development/web

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env/development/pgadmin
    ports:
    - "8080:80"
    volumes:
    - pgadmin:/var/lib/pgadmin
    links:
      - "database:pgsql"

volumes:
  gem_cache:
  pgadmin:
  postgres: